In [17]:
import sys,os
__script_path=os.path.abspath(globals().get('__file__','.'))
__script_dir = os.path.dirname(__script_path)
root_dir = os.path.abspath(f'{__script_dir}/../')
print(root_dir)
for lib in [root_dir][::-1]:
    if lib in sys.path:
        sys.path.remove(lib)
    sys.path.insert(0,lib)

c:\Users\PC\Data\ads_enfit

In [18]:
from libs.common import *
from config.config import *

In [19]:
if os.path.exists(exps_dir) == False: # tạo thư mục (nếu chưa có)
  os.makedirs(exps_dir, exist_ok=True)

save_dir = f"{exps_dir}/prj_exp"
os.makedirs(save_dir, exist_ok=True)

In [20]:
df_train_features=pd.read_csv(f'{save_dir}/df_train_features.csv')
df_test_features=pd.read_csv(f'{save_dir}/df_test_features.csv')
df_train_features

,row_id,county,is_business,product_type,is_consumption,datetime,date,eic_count,installed_capacity,euros_per_mwh,...,day,weekday,month,year,segment,sin(dayofyear),cos(dayofyear),sin(hour),cos(hour),target
0,366048,0,0,1,0,2022-01-01 00:00:00,2022-01-01,148.0,1345.69,65.76,...,1,6,1,2022,0_0_1_0,0.017166,0.999853,0.000000,1.000000,0.000
1,366049,0,0,1,1,2022-01-01 00:00:00,2022-01-01,148.0,1345.69,65.76,...,1,6,1,2022,0_0_1_1,0.017166,0.999853,0.000000,1.000000,442.226
2,366050,0,0,2,0,2022-01-01 00:00:00,2022-01-01,16.0,153.70,65.76,...,1,6,1,2022,0_0_2_0,0.017166,0.999853,0.000000,1.000000,0.000
3,366051,0,0,2,1,2022-01-01 00:00:00,2022-01-01,16.0,153.70,65.76,...,1,6,1,2022,0_0_2_1,0.017166,0.999853,0.000000,1.000000,44.899
4,366052,0,0,3,0,2022-01-01 00:00:00,2022-01-01,739.0,7638.62,65.76,...,1,6,1,2022,0_0_3_0,0.017166,0.999853,0.000000,1.000000,0.015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1651897,2018347,15,1,0,1,2023-05-31 23:00:00,2023-05-31,15.0,620.00,-1.29,...,31,3,5,2023,15_1_0_1,0.522133,-0.852864,-0.258819,0.965926,197.233
1651898,2018348,15,1,1,0,2023-05-31 23:00:00,2023-05-31,20.0,624.50,-1.29,...,31,3,5,2023,15_1_1_0,0.522133,-0.852864,-0.258819,0.965926,0.000
1651899,2018349,15,1,1,1,2023-05-31 23:00:00,2023-05-31,20.0,624.50,-1.29,...,31,3,5,2023,15_1_1_1,0.522133,-0.852864,-0.258819,0.965926,28.404
1651900,2018350,15,1,3,0,2023-05-31 23:00:00,2023-05-31,55.0,2188.20,-1.29,...,31,3,5,2023,15_1_3_0,0.522133,-0.852864,-0.258819,0.965926,0.000
1651901,2018351,15,1,3,1,2023-05-31 23:00:00,2023-05-31,55.0,2188.20,-1.29,...,31,3,5,2023,15_1_3_1,0.522133,-0.852864,-0.258819,0.965926,196.240

In [21]:
df_test_features.drop_duplicates(inplace=True)

In [22]:
df_test_features

,Unnamed: 0,county,is_business,product_type,is_consumption,datetime,row_id,date,eic_count,installed_capacity,...,total_precipitation_fl,day,weekday,month,year,segment,sin(dayofyear),cos(dayofyear),sin(hour),cos(hour)
0,0,0,0,1,0,2023-05-28 00:00:00,2005872,2023-05-28,507,4960.215,...,0.0,28,7,5,2023,0_0_1_0,0.565345,-0.824855,0.000000,1.000000
1,1,0,0,1,1,2023-05-28 00:00:00,2005873,2023-05-28,507,4960.215,...,0.0,28,7,5,2023,0_0_1_1,0.565345,-0.824855,0.000000,1.000000
2,2,0,0,2,0,2023-05-28 00:00:00,2005874,2023-05-28,11,34.000,...,0.0,28,7,5,2023,0_0_2_0,0.565345,-0.824855,0.000000,1.000000
3,3,0,0,2,1,2023-05-28 00:00:00,2005875,2023-05-28,11,34.000,...,0.0,28,7,5,2023,0_0_2_1,0.565345,-0.824855,0.000000,1.000000
4,4,0,0,3,0,2023-05-28 00:00:00,2005876,2023-05-28,1516,15977.560,...,0.0,28,7,5,2023,0_0_3_0,0.565345,-0.824855,0.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12475,12475,15,1,0,1,2023-05-31 23:00:00,2018347,2023-05-31,15,620.000,...,0.0,31,3,5,2023,15_1_0_1,0.522133,-0.852864,-0.258819,0.965926
12476,12476,15,1,1,0,2023-05-31 23:00:00,2018348,2023-05-31,20,624.500,...,0.0,31,3,5,2023,15_1_1_0,0.522133,-0.852864,-0.258819,0.965926
12477,12477,15,1,1,1,2023-05-31 23:00:00,2018349,2023-05-31,20,624.500,...,0.0,31,3,5,2023,15_1_1_1,0.522133,-0.852864,-0.258819,0.965926
12478,12478,15,1,3,0,2023-05-31 23:00:00,2018350,2023-05-31,55,2188.200,...,0.0,31,3,5,2023,15_1_3_0,0.522133,-0.852864,-0.258819,0.965926
12479,12479,15,1,3,1,2023-05-31 23:00:00,2018351,2023-05-31,55,2188.200,...,0.0,31,3,5,2023,15_1_3_1,0.522133,-0.852864,-0.258819,0.965926

In [23]:
df_train_features=df_train_features.drop(columns=['date', 'datetime'])
df_test_features=df_test_features.drop(columns=['date', 'datetime'])
# df.isnull().sum()
# df_train_features.dropna(inplace=True)
print(df_train_features.shape, df_test_features.shape)

(1651902, 44) (12480, 44)

In [24]:
df_train_features.isnull().sum()

row_id                                      0
county                                      0
is_business                                 0
product_type                                0
is_consumption                              0
eic_count                                2400
installed_capacity                       2400
euros_per_mwh                             268
hours_ahead                                 0
temperature                                 0
dewpoint                                    0
cloudcover_high                             0
cloudcover_low                              0
cloudcover_mid                              0
cloudcover_total                            0
10_metre_u_wind_component                   0
10_metre_v_wind_component                   0
direct_solar_radiation                      0
surface_solar_radiation_downwards           0
snowfall                                    0
total_precipitation                         0
hours_ahead_fl                          24762
temperature_fl                          24762
dewpoint_fl                             24762
cloudcover_high_fl                      24762
cloudcover_low_fl                       24762
cloudcover_mid_fl                       24762
cloudcover_total_fl                     24762
10_metre_u_wind_component_fl            24762
10_metre_v_wind_component_fl            24762
direct_solar_radiation_fl               24762
surface_solar_radiation_downwards_fl    24762
snowfall_fl                             24762
total_precipitation_fl                  24762
day                                         0
weekday                                     0
month                                       0
year                                        0
segment                                     0
sin(dayofyear)                              0
cos(dayofyear)                              0
sin(hour)                                   0
cos(hour)                                   0
target                                      0
dtype: int64

In [25]:
df_test_features.isnull().sum()

Unnamed: 0                                0
county                                    0
is_business                               0
product_type                              0
is_consumption                            0
row_id                                    0
eic_count                                 0
installed_capacity                        0
euros_per_mwh                             0
hours_ahead                               0
temperature                               0
dewpoint                                  0
cloudcover_high                           0
cloudcover_low                            0
cloudcover_mid                            0
cloudcover_total                          0
10_metre_u_wind_component                 0
10_metre_v_wind_component                 0
direct_solar_radiation                    0
surface_solar_radiation_downwards         0
snowfall                                  0
total_precipitation                       0
hours_ahead_fl                          192
temperature_fl                          192
dewpoint_fl                             192
cloudcover_high_fl                      192
cloudcover_low_fl                       192
cloudcover_mid_fl                       192
cloudcover_total_fl                     192
10_metre_u_wind_component_fl            192
10_metre_v_wind_component_fl            192
direct_solar_radiation_fl               192
surface_solar_radiation_downwards_fl    192
snowfall_fl                             192
total_precipitation_fl                  192
day                                       0
weekday                                   0
month                                     0
year                                      0
segment                                   0
sin(dayofyear)                            0
cos(dayofyear)                            0
sin(hour)                                 0
cos(hour)                                 0
dtype: int64

In [26]:
df_test_features

,Unnamed: 0,county,is_business,product_type,is_consumption,row_id,eic_count,installed_capacity,euros_per_mwh,hours_ahead,...,total_precipitation_fl,day,weekday,month,year,segment,sin(dayofyear),cos(dayofyear),sin(hour),cos(hour)
0,0,0,0,1,0,2005872,507,4960.215,87.54,46.0,...,0.0,28,7,5,2023,0_0_1_0,0.565345,-0.824855,0.000000,1.000000
1,1,0,0,1,1,2005873,507,4960.215,87.54,46.0,...,0.0,28,7,5,2023,0_0_1_1,0.565345,-0.824855,0.000000,1.000000
2,2,0,0,2,0,2005874,11,34.000,87.54,46.0,...,0.0,28,7,5,2023,0_0_2_0,0.565345,-0.824855,0.000000,1.000000
3,3,0,0,2,1,2005875,11,34.000,87.54,46.0,...,0.0,28,7,5,2023,0_0_2_1,0.565345,-0.824855,0.000000,1.000000
4,4,0,0,3,0,2005876,1516,15977.560,87.54,46.0,...,0.0,28,7,5,2023,0_0_3_0,0.565345,-0.824855,0.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12475,12475,15,1,0,1,2018347,15,620.000,-1.29,45.0,...,0.0,31,3,5,2023,15_1_0_1,0.522133,-0.852864,-0.258819,0.965926
12476,12476,15,1,1,0,2018348,20,624.500,-1.29,45.0,...,0.0,31,3,5,2023,15_1_1_0,0.522133,-0.852864,-0.258819,0.965926
12477,12477,15,1,1,1,2018349,20,624.500,-1.29,45.0,...,0.0,31,3,5,2023,15_1_1_1,0.522133,-0.852864,-0.258819,0.965926
12478,12478,15,1,3,0,2018350,55,2188.200,-1.29,45.0,...,0.0,31,3,5,2023,15_1_3_0,0.522133,-0.852864,-0.258819,0.965926
12479,12479,15,1,3,1,2018351,55,2188.200,-1.29,45.0,...,0.0,31,3,5,2023,15_1_3_1,0.522133,-0.852864,-0.258819,0.965926

In [27]:
df_train_features.dropna(inplace=True)
df_test_features.dropna(inplace=True)
print(len(df_test_features), len(df_train_features))

12288 1624478

In [28]:
# for 'segment' in category_columns:
label_encoder = LabelEncoder()
df_train_features['segment'] = label_encoder.fit_transform(df_train_features['segment'])
df_test_features['segment'] = label_encoder.fit_transform(df_test_features['segment'])

In [29]:
Y=df_train_features['target']
X=df_train_features.drop('target',axis=1)

In [30]:
df_train,df_valid = train_test_split(df_train_features, test_size=0.33, random_state=42, shuffle=False)
print(df_train.shape, df_valid.shape, df_test_features.shape)

(1088400, 44) (536078, 44) (12288, 44)

In [31]:
# df_train_features.to_csv(f'{save_dir}/train_lag{ndays}_pre_processing.csv')
df_train.to_csv(f'{save_dir}/df_train.csv')
df_valid.to_csv(f'{save_dir}/df_valid.csv')

In [32]:

Y.to_csv(f'{save_dir}/y.csv')
X.to_csv(f'{save_dir}/X.csv')